# General Jekyll Config
url: http://www.rtre84.github.com
safe: true
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock, package.json, node_modules]
kramdown:
  input: GFM
  hard_wrap: false
poole:
  default_layout: post
gems:
  - jekyll-redirect-from
excerpt_separator: <!--more-->
